### ISSUE TITLE
compiling

### ISSUE THREAD

**Issue by l33tconsultant** [bitpay/android-sdk#5]
Error:Execution failed for task ':xxx:dexBitcoinDebugServer'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

Seems the maven pull isn't working at all - adding the whole project as a module, or just the aar file gives me this error on compile.

**Comment by l33tconsultant** [comment]
Looks like the new update 1.0 fixed some things, but now when I compile I get a different message:

/Users/user/AndroidStudioProjects/com.sample/app/build/intermediates/res/bitcoin/debug/drawable-hdpi-v4/logo.png: error: Duplicate file.
/Users/user/AndroidStudioProjects/c/com.sample/app/build/intermediates/res/bitcoin/debug/drawable-hdpi/logo.png: Original is here. The version qualifier may be implied.

**Comment by ionux** [comment]
@l33tconsultant thanks for the update on this issue and I apologize for the lateness reviewing it.  I'm looking at this now with a fresh install of Android Studio and a fresh project.  Are you using Eclipse or Android Studio, btw?

**Comment by l33tconsultant** [comment]
I'm using Android Studio.  Thanks for looking into it.

**Comment by ionux** [comment]
@l33tconsultant  I created a test project, imported the SDK and could not replicate the errors you've been experiencing.  However, I believe I found an answer to the duplicate file error here: http://stackoverflow.com/questions/29965398/gradle-finished-with-non-zero-exit-value-1-ic-launcher-png-error-duplicate-fi

>To work around the issue temporarily, add the -v4 qualifier to your drawable resouce folders (or move just ic_launcher.png to *dpi-v4 if you have your reasons) -- credits to Xavier Durochet for the solution. You can also just rename your icon into something else and make corresponding change to AndroidManifest.xml

Let me know if that works to solve this problem, at least.

**Comment by l33tconsultant** [comment]
Indeed.  the file in conflict was "logo.png"  renamed it to my_logo.png , and it now successfully compiles.  I am guilty of using a very generic name ;)  Helps us both!

**Comment by ionux** [comment]
Good deal!  If you run into any more issues, don't hesitate to let me know.
