### ISSUE TITLE
Unrecognized field "bitcoinAddress"

### ISSUE THREAD

**Issue by munibshaukat** [bitpay/android-sdk#9]
Hi, 
We are facing the issue using bitpay android sdk from some days ... was working fine some days before , Please resolve this issue ,,, See log cat error

 W/System.err: com.bitpay.sdk.controller.BitPayException: Error - failed to deserialize BitPay server response (Invoice) : Unrecognized field "bitcoinAddress" (class com.bitpay.sdk.model.Invoice), not marked as ignorable (31 known properties: "itemDesc", "notificationURL", "guid", "price", "transactionSpeed", "orderId", "paymentUrls", "refundAddresses", "buyerFields", "currency", "transactions", "physical", "fullNotifications" [truncated]])
W/System.err:     at [Source: {"facade":"pos/invoice","data":{"url":"https://bitpay.com/invoice?id=xxxxxxxxx","status":"new","btcPrice":"0.024368","btcDue":"0.024368","price":10,"currency":"USD","exRates":{"USD":410.38000000000005},"invoiceTime":1457440854722,"expirationTime":1457441754722,"currentTime":1457440854786,"guid":"96002893","id":xxxxxxxxxxx","btcPaid":"0.000000","rate":410.38,"exceptionStatus":false,"paymentUrls":{"BIP21":"bitcoin:xxxxxxxxxx?amount=0.024368","BIP72":"bitcoin:xxxxxxxxxx?amount=0.024368&r=https://bitpay.com/i/xxxxxxxxxxxxx","BIP72b":"bitcoin:?r=https://bitpay.com/i/xxxxxxxxxS","BIP73":"https://bitpay.com/i/xxxxxxxx"},"bitcoinAddress":"xxxxxxxxxxxxx","token":"xxxxxxxxxxxxxxxxxxxxxxx"}}; line: 1, column: 748] (through reference chain: com.bitpay.sdk.controller.InvoiceWrapper["data"]->com.bitpay.sdk.model.Invoice["bitcoinAddress"])
    at com.bitpay.sdk.controller.BitPay.createInvoice(BitPay.java:199)
   at com.bitpay.sdk.android.BitPayAndroid$CreateInvoiceTask.doInBackground(BitPayAndroid.java:395)
     at com.bitpay.sdk.android.BitPayAndroid$CreateInvoiceTask.doInBackground(BitPayAndroid.java:383)
     at android.os.AsyncTask$2.call(AsyncTask.java:292)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
  at java.lang.Thread.run(Thread.java:831)

Looking forward for your response

**Comment by kleetus** [comment]
thanks for sending in this report. I will fix this ASAP.

**Comment by munibshaukat** [comment]
We are still having the same issue following the JsonIgnoreProperties documentation , we use 

 // to prevent specified fields from being serialized or deserialized
 // (i.e. not include in JSON output; or being set even if they were included)
 @JsonIgnoreProperties({ "bitcoinAddress" })

and 

 // To ignore any unknown properties in JSON input without exception:
 @JsonIgnoreProperties(ignoreUnknown=true)


getting the same exception 

Can you please update it and provide the new version of this @aar
compile 'com.bitpay:android-sdk:1.0.0@aar'

Looking forward to hear from you soon

**Comment by kleetus** [comment]
I have a merge request #10 for this issue. It did test out successfully for me. In your last message, you signified that you got the same exception using @JsonIgnoreProperties(ignoreUnknown=true)

If you could attempt to use my code to see if this clears up the issue, then I will get it merged and release an aar.

**Comment by munibshaukat** [comment]
yes you can release a new aar

**Comment by kleetus** [comment]
I've added an aar file to the dist directory as well as updated sonatype. I am waiting for the changes to show up on sonatype.
